---

- hosts: tnode
  vars_files: vars_maxdays.yml

  tasks:
    - name: Charge Password Maxdays
      ansible.builtin.user:
        name: "{{ item.username }}"
        password_expire_max: "{{ item.maxdays }}"
      loop: "{{ Userinfo }}"




