---
# tasks file for myrole.nfs_server

- name: Install NFS packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ nfs_packages }}"

- name: Create NFS export direcory
  ansible.builtin.file:
    path: "{{ share_path }}"
    state: directory
    owner: root
    group: root
    mode: "0777"

- name: Configure NFS exports
  ansible.builtin.lineinfile:
    path: "/etc/exports"
    line: "{{ share_path }} *(rw,sync,)"
    regexp: "^{{ share_path }}"
    state: present
    create: true
  notify: Restart NFS Service

# AWS의 Cent OS에서는 firewalld를 사용하지 않기 때문에 주석처리
#- name: Add nfs to firewalld
#  ansible.builtin.firewalld:
#    service: "{{ item }}"
#    permanent: true
#    state: enabled
#  loop:
#    - nfp
#    - rpc-bind
#    - mountd
#  notify: Reload firewalld

